"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import "@/sass";
import { Providers } from "./providers";

import Header from "@/components/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    useEffect(() => {}, []);
    return (
        <html lang="en">
            <body
                className={`main main-container`}
                suppressHydrationWarning={true}
            >
                <Header />
                <div className="main">
                    <Providers>{children}</Providers>
                </div>
            </body>
        </html>
    );
}
