"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { VStack, StackDivider } from "@chakra-ui/react";
import "../sass/main.scss";
import { Providers } from "./providers";

import Header from "@components/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    useEffect(() => {}, []);
    return (
        <html lang="en">
            <body>
                <div
                    className={`main  main-container body`}
                    suppressHydrationWarning={true}
                >
                    <Header />
                    <div className="main ">
                        <div className="main-info-container">
                            <Providers>{children}</Providers>
                        </div>
                    </div>
                </div>

            </body>
        </html>
    );
}
