"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { VStack, StackDivider } from "@chakra-ui/react";
import styles from "@sass";
import { Providers } from "./providers";

import Header from "@components/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    useEffect(() => {}, []);
    return (
        <html lang="en">
            <body
                className={`${styles.main} ${styles["main-container"]}`}
                suppressHydrationWarning={true}
            >
                <Header />
                <div className="main ">
                    <div className="main-info-container">
                        <Providers>{children}</Providers>
                    </div>
                </div>
            </body>
        </html>
    );
}
